### ISSUE TITLE
Item Import Amount >64 voids qty's above 64

### ISSUE THREAD

**Issue by shymian** [CyclopsMC/IntegratedTunnels#158]
#### Issue type:

- :bug: Bug

____

#### Short description:

Using an Item Importer, with aspect Item Import Amount, and a variable card >64 will void items. 
 It will extract the full quantity set on the variable card, but only insert 64 items, voiding the remaining amount.  Previously you could extract >64 units by using high variable card amounts (I was running 16k) from mods like Storage Drawers and insert full qty's listed into additional storage mods (ProjectEx EMC Link, Industrial Foregoing Black Hole Unit, etc).  Now it extracts the qty listed on the variable but only inserts a single stack and voids the difference.

#### Steps to reproduce the problem:

Item Importer
Item Import Amount aspect
Variable Card with an Integer >64
Storage mods that store items as full qty's not stacks (Storage Drawers, Dank Null come to mind)
Video Example: https://streamable.com/fcc64

#### Expected behaviour:

Qty's should not be voided.  If extracting 16k units per operation, 16k units should be received by the target block, or be capped at the blocks storage capacity.

Previous Integrated Tunnels version 1.5.6 (Stoneblock 2 1.4.0) worked as intended.

#### Versions:

Minecraft: 1.12.2
Forge: 1.12.2-14.23.5.2808
Integrated Tunnels: 1.12.2-1.6.5
Modpack: Stoneblock 2 1.6.0

#### Log file:
NA

**Comment by rubensworks** [comment]
Please try again with the latest IT (and cyclops mods) versions. This should have been fixed already.

**Comment by shymian** [comment]
Still happens on latest versions when moving between Storage Drawers.

Test Setup Mods:
  Chameleon-1.12-4.1.3
  CommonCapabilities-1.12.2-2.0.4
  CyclopsCore-1.12.2-1.0.5
  IntegratedDynamics-1.12.2-1.0.7
  IntegratedTunnels-1.12.2-1.6.7
  ProjectE-1.12.2-PE1.4.0
  StorageDrawers-1.12.2-5.3.8

Log: https://paste.ee/p/Txwu4

**Comment by rubensworks** [comment]
Thanks for checking, will try to look into it soon.

**Comment by rubensworks** [comment]
Note to self: this only occurs with importer->interface, but not for interface->exporter.
